# Generated by Django 6.0.4 on 2026-05-20 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.CharField(max_length=255, verbose_name='Enunciado da Pergunta')),
                ('opcao_a', models.CharField(max_length=255, verbose_name='Opção A')),
                ('opcao_b', models.CharField(max_length=255, verbose_name='Opção B')),
                ('opcao_c', models.CharField(max_length=255, verbose_name='Opção C')),
                ('resposta_correta', models.CharField(choices=[('A', 'Opção A'), ('B', 'Opção B'), ('C', 'Opção C')], max_length=1, verbose_name='Resposta Correta')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='users.atividade')),
            ],
            options={
                'verbose_name': 'Pergunta',
                'verbose_name_plural': 'Perguntas',
            },
        ),
    ]
